### PR TITLE
build: add developers section

### PR DESCRIPTION
**Pull request by mlopezFC**

### CODE REVIEW

**Review by javier-godoy — CHANGES_REQUESTED** [review]
Commits of type `build:` indicate _changes to the build process or external dependencies affecting the exported artifacts_, which isn't the case.

**Comment by mlopezFC** [comment]
From a certain perspective, this is modifying the pom itself as a exported artifact (by adding more metadata), so it's like a gray area.

**Comment by javier-godoy** [comment]
> From a certain perspective, this is modifying the pom itself as a exported artifact (by adding more metadata), so it's like a gray area.

According to our Commit Message Guidelines version 1.0.0-rc.5, you are absolutely right. The discussion in https://github.com/FlowingCode/DevelopmentConventions/issues/10 seems to suggest the need for futher clarification.

**Review by javier-godoy — APPROVED** [review]
Approving since the commit message guidelines are correctly applied.

**Pull request merged**
